name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Compile for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            bin: target/release/roaming_proxy
          - os: windows-latest
            bin: target/release/roaming_proxy.exe

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.bin }}
